- name: add 'chris lea' PPA for Redis
  sudo: true
  apt_repository: repo=ppa:chris-lea/redis-server
  register: result

- name: apt-get update
  sudo: true
  apt: update_cache=yes
  when: result.changed

- name: install 'redis-server'
  sudo: true
  apt: pkg=redis-server state=latest
  register: result

- name: disable 'redis-server'
  sudo: true
  service: name=redis-server enabled=no state=stopped
  when: result.changed

- name: create redis data dir
  sudo: true
  file: path={{ redis_option_dir }}
        state=directory
        owner=redis
        group=redis
        recurse=yes

- name: generate upstart script
  sudo: true
  template:
    src='upstart.conf.j2'
    dest={{ redis_initfile }}
  notify: restart redis

- name: generate config file
  sudo: true
  template:
    src='redis.conf.j2'
    owner=redis
    group=redis
    dest={{ redis_conffile }}
  notify: restart redis

- name: remove default redis config
  sudo: true
  file: path=/etc/redis/redis.conf state=absent
  when: redis_conffile != '/etc/redis/redis.conf'
